### ISSUE TITLE
Prepare a pattern of puzzle

### ISSUE THREAD

**Issue by axross** [axross/ciccc-treesandtents#14]
- Come up with or copy from somewhere
- Consider a data type of it

**Comment by axross** [comment]
We will implement just one pattern of puzzle (5x5)
After we have implemented everything, we’ll extend it to be more than one pattern

**Comment by EriMiwa** [comment]
![Screenshot_20190322_134602_com frozax tentsandtrees](https://user-images.githubusercontent.com/45449908/54887489-f5d15e00-4e50-11e9-8833-ca7dd1fc8382.jpg)
![Screenshot_20190323_205458_com frozax tentsandtrees](https://user-images.githubusercontent.com/45449908/54887490-f5d15e00-4e50-11e9-9ea5-0ca41ac45c9e.jpg)
![Screenshot_20190322_134332_com frozax tentsandtrees](https://user-images.githubusercontent.com/45449908/54887491-f5d15e00-4e50-11e9-97bb-09474a73324a.jpg)
![Screenshot_20190323_202939_com frozax tentsandtrees](https://user-images.githubusercontent.com/45449908/54887492-f669f480-4e50-11e9-810d-636d02c667cb.jpg)
![Screenshot_20190322_134445_com frozax tentsandtrees](https://user-images.githubusercontent.com/45449908/54887493-f669f480-4e50-11e9-8fc7-4f861497da84.jpg)
![Screenshot_20190322_135201_com frozax tentsandtrees](https://user-images.githubusercontent.com/45449908/54887494-f669f480-4e50-11e9-9745-c800bdf536ee.jpg)

**Comment by daniellecalmon** [comment]
Hi guys! I made "Consider a data type of it" together with issue #32. 
Can you guys review these patterns?
