### ISSUE TITLE
Design how the game board screen looks

### ISSUE THREAD

**Issue by axross** [axross/ciccc-treesandtents#20]
![IMG_20190327_154131](https://user-images.githubusercontent.com/4289883/55120319-b5711a80-50b2-11e9-8179-d446bc6a36c9.jpg)

**Comment by axross** [comment]
@EriMiwa @danismgomes @SyllindaCardoso 

I've just created images for game board screen. Do you have any comment for this?

![game board screen](https://user-images.githubusercontent.com/4289883/55120389-0f71e000-50b3-11e9-902e-d20ac4225f25.png)

![while solving](https://user-images.githubusercontent.com/4289883/55120393-11d43a00-50b3-11e9-9219-fafea5b29c32.png)

**Comment by EriMiwa** [comment]
@axross thanks for making board design! it looks so pretty!;-)
I have one thing I wanna ask you. If a player arranges 2 dogs in vertical, how can we implement these layered illustrations?

**Comment by EriMiwa** [comment]
@axross sorry, one more thing we need to put a function! it is checked sign beside of numbers. (if dogs number much or not with numbers)

**Comment by axross** [comment]
@EriMiwa 

> thanks for making board design! it looks so pretty!;-)
> I have one thing I wanna ask you. If a player arranges 2 dogs in vertical, how can we implement these layered illustrations?

Good question! I think it can be great if the dogs in below appear in front of another ones. I think it's possible with changing `viewOrder` in JavaFX. (ref. https://stackoverflow.com/questions/2988196/z-order-in-javafx)

> sorry, one more thing we need to put a function! it is checked sign beside of numbers. (if dogs number much or not with numbers)

Okay, I'll prepare an image with number checking soon! But It takes more works for implementation. So let we put it as an additional task. (I mean even if you guys feel struggled with displaying check marks, it's okay!)

**Comment by EriMiwa** [comment]
@axross 

> Good question! I think it can be great if the dogs in below appear in front of another ones. I think it's possible with changing viewOrder in JavaFX. (ref. https://stackoverflow.com/questions/2988196/z-order-in-javafx)

I see, it gonna be no problem to implement.

> Okay, I'll prepare an image with number checking soon! But It takes more works for implementation. So let we put it as an additional task. (I mean even if you guys feel struggled with displaying check marks, it's okay!)

OK, if we can find a more simple solution, it's better to choose it. for example, how about a function just changing the number's color to red if a player put the different number of dogs??

**Comment by axross** [comment]
@EriMiwa

Thanks!

> OK, if we can find a more simple solution, it's better to choose it. for example, how about a function just changing the number's color to red if a player put the different number of dogs??

It gonna be pretty much easier, I guess

**Comment by axross** [comment]
Here is a game board with icon.

![playing](https://user-images.githubusercontent.com/4289883/55131734-17467a00-50dd-11e9-813d-4ece216f1458.png)

- Check mark is appeared if the column or row has correct number of dogs
- Cross mark is appeared if the column or row has more dogs than the number indicates
- There's no symbol appeared otherwise

**Comment by EriMiwa** [comment]
it looks great!! thanks, @axross
