### ISSUE TITLE
Draft the rules

### ISSUE THREAD

**Issue by axross** [axross/ciccc-treesandtents#28]
- Review in the team

**Comment by SyllindaCardoso** [comment]
https://docs.google.com/presentation/d/1bUM5a_lxK8m7qLirQG97BZ5-Vm1vTle72Iy_Wh5dUXo/edit?usp=sharing

**Comment by SyllindaCardoso** [comment]
Can you guys check and see you would like to change it, please?

**Comment by axross** [comment]
Yes, I can see it!

However ,"dogs" and "bones" are vice versa in my image. Dogs like bones, so they are coming to bones.

**Comment by SyllindaCardoso** [comment]
Oh OK!!! I thought we were giving the dog a bone.... 
I'll change it then!

**Comment by SyllindaCardoso** [comment]
new rules

https://docs.google.com/presentation/d/1bUM5a_lxK8m7qLirQG97BZ5-Vm1vTle72Iy_Wh5dUXo/edit?usp=sharing

**Comment by axross** [comment]
@EriMiwa
Is there everything you want? If it isn't, please let Syllinda know what thing is omitted.

@SyllindaCardoso 
If so for her, it means done and you can close this issue!

**Comment by EriMiwa** [comment]
@SyllindaCardoso Thanks, Syllinda! I think these rules are perfect for describing our game! I have nothing to add them:)

@axross Thanks! I already talked to her directly in class today. it gonna be no problem so far!

**Comment by axross** [comment]
I got it.
