### ISSUE TITLE
Prepare a slide for the presentation

### ISSUE THREAD

**Issue by axross** [axross/ciccc-treesandtents#31]

**Comment by SyllindaCardoso** [comment]
https://docs.google.com/presentation/d/1bUM5a_lxK8m7qLirQG97BZ5-Vm1vTle72Iy_Wh5dUXo/edit#slide=id.g559c8fa38d_0_12

Hey guys! 
I described the rules of the game and where the idea came from. 
I was thinking about including Missy's photo and say that our idea of creating 'Dogs and Bones' came from her and include a picture of the dog and bone to illustrate each slide. 
What do you think? 
What else shall I include in the presentation?

**Comment by SyllindaCardoso** [comment]
https://docs.google.com/presentation/d/1bUM5a_lxK8m7qLirQG97BZ5-Vm1vTle72Iy_Wh5dUXo/edit#slide=id.g5633fa7de7_0_25

This is my slide so far! 
Would anyone like to add anything else?

**Comment by axross** [comment]
@SyllindaCardoso It would be better if there's the following things in the slide:

- Concise description of the game at first
- No description about rules in **text** (it's better describing the rules in playing the game in practice)
- What kind of things are difficult for us
- How to deal with them
- Outcomes through this project
