### ISSUE TITLE
Create game board with initial state

### ISSUE THREAD

**Issue by daniellecalmon** [axross/ciccc-treesandtents#32]

**Comment by daniellecalmon** [comment]
Hi guys! Could anyone review my code? Thanks!

**Comment by EriMiwa** [comment]
@danismgomes thanks for making it! it looks great!

**Comment by daniellecalmon** [comment]
Thank you @EriMiwa ! Could you make review and if it is ok, approve the pull request?

**Comment by SyllindaCardoso** [comment]
It looks great! you can close this issue

**Comment by axross** [comment]
Please respond in a "review" for pull request, not comment. If you guys forgot how to review, let me know!
